In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

import statsmodels.api as sm
from sklearn.neighbors import NearestNeighbors

import joblib

import sys
import os
sys.path.append(os.path.abspath('..'))

from BettingStrategy.ModelStrategy.LogisticRegression.get_train_test import TrainTestBuilder
from betting_strategy import betting_pipeline, display_bet_dfs
import shap

c:\Users\jcmar\my_files\SportsBetting\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Use github actions to run webscraping tool to search for odds updates twice a day 

see build_datasets.py, set gent_next_fight_stats_odds = True, generate_model_df = True 

yaml file: 
name: Run Script

on:
  schedule:
    - cron: '0 0,12 * * *'   # runs at 00:00 and 12:00 UTC
  workflow_dispatch:         # optional: lets you run it manually

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python your_script.py


Check if new fight opening odds available, 
Send email if true

In [9]:
import re

In [13]:
df = pd.read_csv(r'C:\Users\jcmar\my_files\SportsBetting\Data\upcoming_events\upcoming_stats_2026-03-14.csv')

def height_inches(height):

    if height == '--':
        return None

    if pd.isna(height) is True: 
        return pd.NA

    height = height.replace("HEIGHT: ","")
    match = re.match(r"(\d+)' (\d+)", height)
    if match:
        feet = int(match.group(1))
        inches = int(match.group(2))
        total_inches = feet * 12 + inches
        return total_inches
    

df['height_blue'].apply(height_inches)

0     67
1     65
2     76
3     71
4     68
      ..
74    76
75    68
76    68
77    74
78    72
Name: height_blue, Length: 79, dtype: object

In [12]:
df['height_blue'].isna().sum()

np.int64(1)

In [ ]:
import smtplib
from email.mime.text import MIMEText

sender = "your_email@gmail.com"
receiver = "target_email@gmail.com"
app_password = "your_app_password"

msg = MIMEText("Hello, this email was sent from Python.")
msg["Subject"] = "Python Test Email"
msg["From"] = sender
msg["To"] = receiver

with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
    server.login(sender, app_password)
    server.sendmail(sender, receiver, msg.as_string())

print("Email sent!")

In [2]:
date = '2026-03-07'
upcoming_fp = fr'C:\Users\jcmar\my_files\SportsBetting\Data\upcoming_events\event_dfs\upcoming_odds_stats_{date}.csv'
upcoming_df = pd.read_csv(upcoming_fp)  

upcoming_df['math_red'] = upcoming_df['math_red'].astype('category')
upcoming_df['math_blue'] = upcoming_df['math_blue'].astype('category')
upcoming_df['elo_pred'] = upcoming_df['elo_pred'].astype('category')

In [22]:
open_feats = [
                  'proba_fair_open_diff', 'reach_diff', 
                  
                  'sub_att_pm_red', 'sub_att_pm_blue',
                  'ratio_control_diff',

                  'td_landed_pm_diff',  
                  'ratio_td_diff', 
                  'adjusted_td_red', 'adjusted_td_blue',

                  'sig_str_absorbed_total_diff', 
                  'sig_str_accuracy_pct_diff',
                  'sig_str_defense_pct_diff',
                  'adjusted_sig_str_blue', 'adjusted_sig_str_red', 
                  
                  'win_pct_red', 'win_pct_blue',
                  'win_streak_diff', 'lose_streak_diff',
                  'elo_red', 'elo_blue', 'elo_pred', 'age_red', 'age_blue'
                  ]

scaler_open = joblib.load("C:\\Users\\jcmar\\my_files\\SportsBetting\\data\\saved_models\\scaler_open.pkl")

In [ ]:
for c in upcoming_df.columns:
    print(c, upcoming_df[c].isna().sum())

In [3]:
model_open = sm.load("C:\\Users\\jcmar\\my_files\\SportsBetting\\data\\saved_models\\logit_model_open.pkl")
model_close1 = sm.load("C:\\Users\\jcmar\\my_files\\SportsBetting\\data\\saved_models\\logit_model_close1.pkl")
model_close2 = sm.load("C:\\Users\\jcmar\\my_files\\SportsBetting\\data\\saved_models\\logit_model_close2.pkl")

scaler_open = joblib.load("C:\\Users\\jcmar\\my_files\\SportsBetting\\data\\saved_models\\scaler_open.pkl")
scaler_close1 = joblib.load("C:\\Users\\jcmar\\my_files\\SportsBetting\\data\\saved_models\\scaler_close1.pkl")
scaler_close2 = joblib.load("C:\\Users\\jcmar\\my_files\\SportsBetting\\data\\saved_models\\scaler_close2.pkl")

open_feats = [
                  'proba_fair_open_diff', 'reach_diff', 
                  
                  'sub_att_pm_red', 'sub_att_pm_blue',
                  'ratio_control_diff',

                  'td_landed_pm_diff',  
                  'ratio_td_diff', 
                  'adjusted_td_red', 'adjusted_td_blue',

                  'sig_str_absorbed_total_diff', 
                  'sig_str_accuracy_pct_diff',
                  'sig_str_defense_pct_diff',
                  'adjusted_sig_str_blue', 'adjusted_sig_str_red', 
                  
                  'win_pct_red', 'win_pct_blue',
                  'win_streak_diff', 'lose_streak_diff',
                  'elo_red', 'elo_blue', 'elo_pred', 'age_red', 'age_blue'
                  ]


close1_feats = [
                  'proba_fair_close1_diff', 'proba_fair_open_diff', 'reach_diff', 
                  'td_landed_total_diff', 'ratio_control_diff', 'sig_str_absorbed_total_diff', 'sig_str_landed_pm_diff', 
                  'sig_str_defense_pct_diff', 'td_attempted_pm_diff',
                  'lose_streak_diff', 'win_pct_diff', 'kd_pm_diff', 'win_streak_diff', 'ko_wins_diff', 'ko_losses_diff', 
                  'elo_red', 'elo_blue', 'age_red', 'age_blue'
                  ]

close2_feats = [
                  'proba_fair_close2_diff', 'proba_fair_open_diff', 'reach_diff', 
                  'td_landed_total_diff', 'ratio_control_diff', 'sig_str_absorbed_total_diff', 'sig_str_landed_pm_diff', 
                  'sig_str_defense_pct_diff', 'td_attempted_pm_diff',
                  'win_pct_diff', 
                  'elo_red', 'elo_blue', 'age_red', 'age_blue'
                  ]

feats_list = [open_feats, close1_feats, close2_feats]
model_list = [model_open, model_close1, model_close2]
scaler_list = [scaler_open, scaler_close1, scaler_close2]

type_list = ['open', 'close1', 'close2']
fair_odds_list = [['dec_fair_open_blue', 'dec_fair_open_red'], ['dec_fair_close1_blue', 'dec_fair_close1_red'], ['dec_fair_close2_blue', 'dec_fair_close2_red']]
real_odds_list = [['dec_open_blue', 'dec_open_red'], ['dec_close1_blue', 'dec_close1_red'], ['dec_close2_blue', 'dec_close2_red'] ]

df_bets_all, df_parlay_all = betting_pipeline(upcoming_df, 
                                            feats_list=feats_list, model_list=model_list, scaler_list=scaler_list, type_list=type_list,
                                            fair_odds_list=fair_odds_list, real_odds_list=real_odds_list, 
                                            bankroll=500, max_drawdown=0.15, N=1000)

here
here
here

In [4]:
df_bets_all[['open_red', 'open_blue', 'close1_red', 'close1_blue', 'close2_red', 'close2_blue']] = upcoming_df[['open_red', 'open_blue', 'close1_red', 'close1_blue', 'close2_red', 'close2_blue']]

df_bets_arr, df_parlay_arr = display_bet_dfs(df_bets_all, df_parlay_all, type_list)
df_bets_arr[0].head(20)

,fighter_red,fighter_blue,pred_name_open,pred_winner_open,choice_proba_open,open_red,open_blue,fstar_open,stake_open,ev_open,edge_open
0,cody garbrandt,xiao long,xiao long,0,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN
1,max holloway,charles oliveira,charles oliveira,0,0.559670,-150.0,130.0,0.040269,20.134534,0.345303,0.124887
2,caio borralho,reinier de ridder,caio borralho,1,0.688363,-235.0,180.0,0.000000,0.000000,0.016230,-0.013130
3,rob font,raul rosas jr,raul rosas jr,0,0.883054,375.0,-500.0,0.113036,56.518159,0.078444,0.049720
4,drew dober,michael johnson,michael johnson,0,0.553430,160.0,-185.0,0.000000,0.000000,-0.127638,-0.095693
5,gregory rodrigues,brunno ferreira,gregory rodrigues,1,0.648236,-150.0,130.0,0.056873,28.436254,0.110026,0.048236
6,donte johnson,dusko todorovic,dusko todorovic,0,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN
7,ricky turcios,alberto montes,alberto montes,0,NaN,190.0,-225.0,0.000000,0.000000,NaN,NaN
8,sumudaerji,jesus aguilar,sumudaerji,1,0.722625,-215.0,185.0,0.068390,34.194901,0.080922,0.040085
9,joosang yoo,gaston bolanos,gaston bolanos,0,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN
10,luke fernandez,rodolfo bellato,rodolfo bellato,0,NaN,-125.0,105.0,0.000000,0.000000,NaN,NaN
11,cody durden,nyamjargal tumendemberel,nyamjargal tumendemberel,0,0.642328,140.0,-160.0,0.058037,29.018710,0.068983,0.026943

In [10]:
df_bets_arr[0][df_bets_arr[0]['fstar_open'] != 0]

,fighter_red,fighter_blue,pred_name_open,pred_winner_open,choice_proba_open,open_red,open_blue,fstar_open,stake_open,ev_open,edge_open
2,israel adesanya,joe pyfer,joe pyfer,0,0.667242,-110.0,-110.0,0.050686,25.342764,0.334484,0.143433

In [27]:
df_bets_arr[1].head(20)

,fighter_red,fighter_blue,pred_name_close1,pred_winner_close1,choice_proba_close1,close1_red,close1_blue,fstar_close1,stake_close1,ev_close1,edge_close1
0,natalia silva,rose namajunas,natalia silva,1,0.807789,-500.0,310.0,0.000000,0.000000,-0.000232,-0.025545
1,kayla harrison,amanda nunes,kayla harrison,1,0.709203,-245.0,130.0,0.000000,0.000000,0.091481,-0.000942
2,sean omalley,song yadong,sean omalley,1,0.661578,-225.0,163.0,0.000000,0.000000,-0.000636,-0.030730
3,waldo cortes acosta,derrick lewis,waldo cortes acosta,1,0.798426,-333.0,225.0,0.075261,37.630292,0.078303,0.029373
4,ateba gautier,andrey pulyaev,ateba gautier,1,0.832048,-1200.0,500.0,0.000000,0.000000,-0.077144,-0.091029
5,arnold allen,jean silva,jean silva,0,0.645086,163.0,-280.0,0.000000,0.000000,-0.065748,-0.091757
6,umar nurmagomedov,deiveson figueiredo,umar nurmagomedov,1,0.920489,-2500.0,700.0,0.000000,0.000000,-0.027304,-0.041049
7,michael johnson,alexander hernandez,alexander hernandez,0,0.689310,145.0,-215.0,0.021327,10.663345,0.070454,0.006771
8,nikita krylov,modestas bukauskas,modestas bukauskas,0,0.571107,130.0,-195.0,0.000000,0.000000,-0.077394,-0.089910
9,alex perez,charles johnson,charles johnson,0,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN
10,josh hokit,denzel freeman,josh hokit,1,0.664326,-275.0,168.0,0.000000,0.000000,-0.038673,-0.069008
11,ricky turcios,cameron smotherman,cameron smotherman,0,0.642763,160.0,-225.0,0.000000,0.000000,-0.026305,-0.049544
12,adam fugitt,ty miller,ty miller,0,NaN,260.0,-425.0,0.000000,0.000000,NaN,NaN
13,justin gaethje,paddy pimblett,paddy pimblett,0,0.790948,176.0,-250.0,0.069356,34.678083,0.157711,0.076663

In [122]:
df_bets_arr[2].head(20)

,fighter_red,fighter_blue,pred_name_close2,pred_winner_close2,choice_proba_close2,close2_red,close2_blue,fstar_close2,stake_close2,ev_close2,edge_close2
0,natalia silva,rose namajunas,natalia silva,1,0.787143,-430.0,350.0,0.000000,0.000000,-0.015695,-0.024178
1,kayla harrison,amanda nunes,kayla harrison,1,0.674967,-155.0,190.0,0.051849,25.924444,0.073083,0.067124
2,sean omalley,song yadong,sean omalley,1,0.670930,-200.0,175.0,0.012789,6.394392,0.026321,0.004263
3,waldo cortes acosta,derrick lewis,waldo cortes acosta,1,0.777148,-300.0,270.0,0.070952,35.475969,0.047044,0.027148
4,ateba gautier,andrey pulyaev,ateba gautier,1,0.830059,-800.0,600.0,0.000000,0.000000,-0.056423,-0.058830
5,arnold allen,jean silva,jean silva,0,0.672887,235.0,-225.0,0.000000,0.000000,-0.033337,-0.019420
6,umar nurmagomedov,deiveson figueiredo,umar nurmagomedov,1,0.915955,-1408.0,950.0,0.000000,0.000000,-0.011502,-0.017732
7,michael johnson,alexander hernandez,alexander hernandez,0,0.683407,165.0,-170.0,0.053980,26.989824,0.090770,0.053777
8,nikita krylov,modestas bukauskas,modestas bukauskas,0,0.534449,155.0,-150.0,0.000000,0.000000,-0.114512,-0.065551
9,alex perez,charles johnson,charles johnson,0,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN
10,josh hokit,denzel freeman,josh hokit,1,0.728014,-220.0,205.0,0.061262,30.630783,0.068859,0.040514
11,ricky turcios,cameron smotherman,cameron smotherman,0,0.630420,172.0,-185.0,0.000000,0.000000,-0.017789,-0.018703
12,adam fugitt,ty miller,ty miller,0,NaN,300.0,-350.0,0.000000,0.000000,NaN,NaN
13,justin gaethje,paddy pimblett,paddy pimblett,0,0.758364,200.0,-220.0,0.063639,31.819439,0.117154,0.070864