In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

import sys
import os
from pathlib import Path

# move upward until we find repo root
repo_root = Path.cwd()

while not (repo_root / ".git").exists():
    repo_root = repo_root.parent

sys.path.append(str(repo_root))
from config import config
from DataPipeline.utils.bets_utils import generate_bets

In [3]:
non_merged = pd.read_csv(r'C:\Users\jcmar\my_files\SportsBetting\Data\non_merged_features\non_merged_stats.csv')
non_merged.iloc[-1]['event_date']

'2026-08-01'

In [5]:
stats_history = pd.read_csv(config.stats_history_file_string) # frames BEFORE any feature engineering 
stats_history.iloc[-1]['event_date']

'2026-02-21'

In [28]:
folder_path = r"C:\Users\jcmar\my_files\SportsBetting\Data\upcoming_events\event_features"

file_path = os.path.join(folder_path, "upcoming_odds_stats_2026-08-08.csv")
print(file_path)

upcoming_fp = fr'{file_path}'
upcoming_df = pd.read_csv(upcoming_fp)  

df_bets_all, df_parlay_all = generate_bets(upcoming_df, select_odds=None)

C:\Users\jcmar\my_files\SportsBetting\Data\upcoming_events\event_features\upcoming_odds_stats_2026-08-08.csv

In [29]:
test_columns = [
    'date', 'fstar_open', 'fstar_close1', 'fstar_close2',
    'pred_name_close1', 'pred_name_close2', 'pred_winner_close1',  'pred_winner_close2',
    'pred_winner_close1_stack', 'pred_winner_close2_stack', 'pred_name_close1_stack', 'pred_name_close2_stack'
   
]
df_bets_all[test_columns]

,date,fstar_open,fstar_close1,fstar_close2,pred_name_close1,pred_name_close2,pred_winner_close1,pred_winner_close2,pred_winner_close1_stack,pred_winner_close2_stack,pred_name_close1_stack,pred_name_close2_stack
0,2026-08-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-08-08,0.000000,0.000000,0.000000,steven asplund,steven asplund,1.0,1.0,1.0,1.0,steven asplund,steven asplund
2,2026-08-08,0.062792,0.000000,0.000000,juliana miller,juliana miller,1.0,1.0,1.0,1.0,juliana miller,juliana miller
3,2026-08-08,0.000000,0.000000,0.000000,miles johns,miles johns,1.0,1.0,1.0,1.0,miles johns,miles johns
4,2026-08-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2026-08-08,0.073664,0.150746,0.154481,diyar nurgozhay,diyar nurgozhay,1.0,1.0,1.0,1.0,diyar nurgozhay,diyar nurgozhay
6,2026-08-08,0.000000,0.000000,0.000000,ty miller,ty miller,0.0,0.0,0.0,0.0,ty miller,ty miller
7,2026-08-08,0.051329,0.000000,0.000000,alexia thainara,alexia thainara,0.0,0.0,0.0,0.0,alexia thainara,alexia thainara
8,2026-08-08,0.000000,0.000000,0.000000,yadier del valle,yadier del valle,0.0,0.0,0.0,0.0,yadier del valle,yadier del valle
9,2026-08-08,0.079930,0.104891,0.122480,diego ferreira,diego ferreira,1.0,1.0,1.0,1.0,diego ferreira,diego ferreira
10,2026-08-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2026-08-08,0.000000,0.000000,0.000000,quillan salkilld,quillan salkilld,0.0,0.0,1.0,1.0,mateusz gamrot,mateusz gamrot

In [27]:
test_columns = ['fstar_close1_stack', 'fstar_close2_stack']
df_bets_all[test_columns]

    fstar_close1_stack  fstar_close2_stack
0                  NaN                 NaN
1             0.220394            0.217955
2             0.227546            0.227752
3             0.178710            0.179392
4                  NaN                 NaN
5             0.190027            0.192303
6             0.000000            0.000000
7             0.222523            0.220643
8             0.000000            0.000000
9             0.201015            0.201898
10                 NaN                 NaN
11            0.126755            0.126545

In [17]:
df_bets_all.columns

Index(['date', 'fighter_red', 'fighter_blue', 'open_red', 'open_blue',
       'close1_red', 'close2_red', 'close1_blue', 'close2_blue',
       'pred_name_open', 'pred_winner_open', 'choice_proba_open', 'fstar_open',
       'stake_open', 'edge_open', 'ev_open', 'pred_name_close1',
       'pred_winner_close1', 'choice_proba_close1', 'fstar_close1',
       'stake_close1', 'edge_close1', 'ev_close1', 'pred_name_close2',
       'pred_winner_close2', 'choice_proba_close2', 'fstar_close2',
       'stake_close2', 'edge_close2', 'ev_close2', 'pred_name_close1_stack',
       'pred_winner_close1_stack', 'choice_proba_close1_stack',
       'fstar_close1_stack', 'stake_close1_stack', 'edge_close1_stack',
       'ev_close1_stack', 'pred_name_close2_stack', 'pred_winner_close2_stack',
       'choice_proba_close2_stack', 'fstar_close2_stack', 'stake_close2_stack',
       'edge_close2_stack', 'ev_close2_stack'],
      dtype='str')