In [1]:
import numpy as np
import pandas as pd
# import seaborn as sns 
# import matplotlib.pyplot as plt 

from collections import defaultdict

# import sys
# sys.path.append(r'C:\Users\jcmar\my_files\SportsBetting\FeatureEngineering\ufc_features')
# sys.path.append(r'C:\Users\jcmar\my_files\SportsBetting\FeatureEngineering')

In [4]:
fp = r'C:\Users\jcmar\my_files\SportsBetting\data\new_combined.csv'
df_combined = pd.read_csv(fp)

fp = r'C:\Users\jcmar\my_files\SportsBetting\data\ufc_new_rolling.csv'
df_rolling = pd.read_csv(fp)

C:\Users\jcmar\AppData\Local\Temp\ipykernel_46876\2176623190.py:2: DtypeWarning: Columns (79,83) have mixed types. Specify dtype option on import or set low_memory=False.
  df_combined = pd.read_csv(fp)

In [5]:
df_combined['ratio_control_red'].isna().sum()

np.int64(772)

In [18]:
print(df_combined.columns[df_combined.columns.duplicated()])

Index([], dtype='object')

In [19]:
fp = r'C:\Users\jcmar\my_files\SportsBetting\data\stats_odds_merged.csv'
df_merged = pd.read_csv(fp)
print(df_merged.columns[df_merged.columns.duplicated()])

Index([], dtype='object')

C:\Users\jcmar\AppData\Local\Temp\ipykernel_46876\1529330230.py:2: DtypeWarning: Columns (79,83) have mixed types. Specify dtype option on import or set low_memory=False.
  df_merged = pd.read_csv(fp)

In [46]:
fp = r'C:\Users\jcmar\my_files\SportsBetting\data\stats_history_2025-11-05.csv'
stats_history = pd.read_csv(fp)


fp = r'C:\Users\jcmar\my_files\SportsBetting\data\odds_history_2025-11-06.csv'
odds_history = pd.read_csv(fp)

In [ ]:
duplicates = odds_history.duplicated(subset=['red_fighter', 'blue_fighter', 'event_date'], keep=False)
dup_rows = odds_history[duplicates]
dup_rows

In [50]:
duplicates = stats_history.duplicated(subset=['fighter_red', 'fighter_blue', 'event_date'], keep=False)
dup_rows = stats_history[duplicates]
dup_rows

Empty DataFrame
Columns: [Unnamed: 0, title_fight, event_name, event_date, event_location, fight_url, weight_class, method, round, fight_time, performance_bonus_winner, fight_otn_bonus, winner, fighter_red, fighter_blue, record_red, record_blue, dob_red, dob_blue, height_red, height_blue, reach_red, reach_blue, stance_red, stance_blue, kd_red, kd_blue, sig_str_red, sig_str_blue, sig_str_percent_red, sig_str_percent_blue, td_red, td_blue, td_pct_red, td_pct_blue, clinch_red, clinch_blue, ground_red, ground_blue, sub_att_red, sub_att_blue, rev_red, rev_blue, ctrl_red, ctrl_blue, head_red, head_blue, body_red, body_blue, leg_red, leg_blue, distance_red, distance_blue, total_strikes_red, total_strikes_blue]
Index: []

[0 rows x 55 columns]

In [74]:
fp = r'C:\Users\jcmar\my_files\SportsBetting\data\entire_odds_stats_2025-11-15.csv'
df_final = pd.read_csv(fp)
df_final.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7995 entries, 0 to 7994
Data columns (total 254 columns):
 #    Column                                Non-Null Count  Dtype
---   ------                                --------------  -----
 0    td_defense_pct_red                    7225 non-null   float64
 1    td_total_attempted_against_red        7225 non-null   float64
 2    td_total_landed_against_red           7225 non-null   float64
 3    td_defense_pct_blue                   6391 non-null   float64
 4    td_total_attempted_against_blue       6391 non-null   float64
 5    td_total_landed_against_blue          6391 non-null   float64
 6    sig_str_defense_pct_red               7225 non-null   float64
 7    sig_str_total_attempted_against_red   7225 non-null   float64
 8    sig_str_total_landed_against_red      7225 non-null   float64
 9    sig_str_defense_pct_blue              6391 non-null   float64
 10   sig_str_total_attempted_against_blue  6391 non-null   float64
 11   sig_str_total_landed_against_blue     6391 non-null   float64
 12   td_accuracy_pct_red                   7225 non-null   float64
 13   td_accuracy_pct_blue                  6391 non-null   float64
 14   sig_str_accuracy_pct_red              7225 non-null   float64
 15   sig_str_accuracy_pct_blue             6391 non-null   float64
 16   kd_pm_red                             7225 non-null   float64
 17   kd_total_red                          7225 non-null   float64
 18   kd_pm_blue                            6391 non-null   float64
 19   kd_total_blue                         6391 non-null   float64
 20   sig_str_landed_pm_red                 7225 non-null   float64
 21   sig_str_landed_total_red              7225 non-null   float64
 22   sig_str_landed_pm_blue                6391 non-null   float64
 23   sig_str_landed_total_blue             6391 non-null   float64
 24   sig_str_absorbed_pm_red               7225 non-null   float64
 25   sig_str_absorbed_total_red            7225 non-null   float64
 26   sig_str_absorbed_pm_blue              6391 non-null   float64
 27   sig_str_absorbed_total_blue           6391 non-null   float64
 28   sig_str_attempted_pm_red              7225 non-null   float64
 29   sig_str_attempted_total_red           7225 non-null   float64
 30   sig_str_attempted_pm_blue             6391 non-null   float64
 31   sig_str_attempted_total_blue          6391 non-null   float64
 32   leg_str_pm_red                        7225 non-null   float64
 33   leg_str_total_red                     7225 non-null   float64
 34   leg_str_pm_blue                       6391 non-null   float64
 35   leg_str_total_blue                    6391 non-null   float64
 36   head_str_pm_red                       7225 non-null   float64
 37   head_str_total_red                    7225 non-null   float64
 38   head_str_pm_blue                      6391 non-null   float64
 39   head_str_total_blue                   6391 non-null   float64
 40   body_str_pm_red                       7225 non-null   float64
 41   body_str_total_red                    7225 non-null   float64
 42   body_str_pm_blue                      6391 non-null   float64
 43   body_str_total_blue                   6391 non-null   float64
 44   clinch_str_pm_red                     7225 non-null   float64
 45   clinch_str_total_red                  7225 non-null   float64
 46   clinch_str_pm_blue                    6391 non-null   float64
 47   clinch_str_total_blue                 6391 non-null   float64
 48   td_landed_pm_red                      7225 non-null   float64
 49   td_landed_total_red                   7225 non-null   float64
 50   td_landed_pm_blue                     6391 non-null   float64
 51   td_landed_total_blue                  6391 non-null   float64
 52   td_attempted_pm_red                   7225 non-null   float64
 53   td_attempted_total_red                7225 non-null   float64
 54   td_attempted_pm_blue                  6391 non-null   float64
 55   td_attempted_total_blue               6391 non-null   float64
 56   control_pm_red                        7225 non-null   float64
 57   control_total_red                     7225 non-null   float64
 58   control_pm_blue                       6391 non-null   float64
 59   control_total_blue                    6391 non-null   float64
 60   sub_att_pm_red                        7225 non-null   float64
 61   sub_att_total_red                     7225 non-null   float64
 62   sub_att_pm_blue                       6391 non-null   float64
 63   sub_att_total_blue                    6391 non-null   float64
 64   reverse_pm_red                        7225 non-null   float64
 65   reverse_total_red                     7225 non-null   float64
 66   reverse_pm_blue                       6391 non-null   float64
 67   reverse_total_blue                    6391 non-null   float64
 68   total_fight_time_red                  7995 non-null   float64
 69   total_fight_time_blue                 7995 non-null   float64
 70   age_red                               7992 non-null   float64
 71   age_blue                              7974 non-null   float64
 72   height_red                            7993 non-null   float64
 73   height_blue                           7993 non-null   float64
 74   reach_red                             7840 non-null   float64
 75   reach_blue                            7442 non-null   float64
 76   date                                  7995 non-null   object
 77   event_location                        7995 non-null   object
 78   weight_class                          7995 non-null   object
 79   title_fight                           7995 non-null   float64
 80   performance_bonus_winner              7995 non-null   float64
 81   fight_otn_bonus                       7995 non-null   float64
 82   method                                7995 non-null   object
 83   winner                                7995 non-null   int64
 84   winner_name                           7995 non-null   object
 85   kd_total_diff                         6068 non-null   float64
 86   kd_pm_diff                            6068 non-null   float64
 87   sig_str_landed_total_diff             6068 non-null   float64
 88   sig_str_landed_pm_diff                6068 non-null   float64
 89   sig_str_absorbed_total_diff           6068 non-null   float64
 90   sig_str_absorbed_pm_diff              6068 non-null   float64
 91   sig_str_attempted_total_diff          6068 non-null   float64
 92   sig_str_attempted_pm_diff             6068 non-null   float64
 93   leg_str_total_diff                    6068 non-null   float64
 94   leg_str_pm_diff                       6068 non-null   float64
 95   head_str_total_diff                   6068 non-null   float64
 96   head_str_pm_diff                      6068 non-null   float64
 97   body_str_total_diff                   6068 non-null   float64
 98   body_str_pm_diff                      6068 non-null   float64
 99   clinch_str_total_diff                 6068 non-null   float64
 100  clinch_str_pm_diff                    6068 non-null   float64
 101  td_landed_total_diff                  6068 non-null   float64
 102  td_landed_pm_diff                     6068 non-null   float64
 103  td_attempted_total_diff               6068 non-null   float64
 104  td_attempted_pm_diff                  6068 non-null   float64
 105  control_total_diff                    6068 non-null   float64
 106  control_pm_diff                       6068 non-null   float64
 107  sub_att_total_diff                    6068 non-null   float64
 108  sub_att_pm_diff                       6068 non-null   float64
 109  reverse_total_diff                    6068 non-null   float64
 110  reverse_pm_diff                       6068 non-null   float64
 111  age_diff                              7971 non-null   float64
 112  height_diff                           7991 non-null   float64
 113  reach_diff                            7318 non-null   float64
 114  avg_fight_min_red                     7225 non-null   float64
 115  avg_fight_min_blue                    6391 non-null   float64
 116  avg_fight_min_diff                    6068 non-null   float64
 117  total_bonus_red                       7225 non-null   float64
 118  total_bonus_blue                      6391 non-null   float64
 119  total_bonus_diff                      6068 non-null   float64
 120  elo_red                               7995 non-null   float64
 121  elo_blue                              7995 non-null   float64
 122  elo_diff                              7995 non-null   float64
 123  glicko_red                            7995 non-null   float64
 124  glicko_blue                           7995 non-null   float64
 125  glicko_rd_red                         7995 non-null   float64
 126  glicko_rd_blue                        7995 non-null   float64
 127  glicko_rd_diff                        7995 non-null   float64
 128  glicko_diff                           7995 non-null   float64
 129  math_red                              7995 non-null   int64
 130  math_blue                             7995 non-null   int64
 131  months_since_red                      7225 non-null   float64
 132  months_since_blue                     6391 non-null   float64
 133  months_since_diff                     6068 non-null   float64
 134  win_streak_red                        7995 non-null   float64
 135  lose_streak_red                       7995 non-null   float64
 136  win_streak_blue                       7995 non-null   float64
 137  lose_streak_blue                      7995 non-null   float64
 138  win_pct_red                           7995 non-null   float64
 139  win_pct_blue                          7995 non-null   float64
 140  num_fights_red                        7995 non-null   float64
 141  num_fights_blue                       7995 non-null   float64
 142  num_wins_red                          7995 non-null   float64
 143  num_wins_blue                         7995 non-null   float64
 144  num_losses_red                        7995 non-null   float64
 145  num_losses_blue                       7995 non-null   float64
 146  num_fights_diff                       7995 non-null   float64
 147  win_streak_diff                       7995 non-null   float64
 148  lose_streak_diff                      7995 non-null   float64
 149  wins_diff                             7995 non-null   float64
 150  losses_diff                           7995 non-null   float64
 151  win_pct_diff                          7995 non-null   float64
 152  decision_wins_red                     7995 non-null   int64
 153  ko_wins_red                           7995 non-null   int64
 154  sub_wins_red                          7995 non-null   int64
 155  decision_wins_blue                    7995 non-null   int64
 156  ko_wins_blue                          7995 non-null   int64
 157  sub_wins_blue                         7995 non-null   int64
 158  decision_wins_diff                    7995 non-null   int64
 159  ko_wins_diff                          7995 non-null   int64
 160  sub_wins_diff                         7995 non-null   int64
 161  ko_pct_red                            7995 non-null   float64
 162  dec_pct_red                           7995 non-null   float64
 163  sub_pct_red                           7995 non-null   float64
 164  ko_pct_blue                           7995 non-null   float64
 165  dec_pct_blue                          7995 non-null   float64
 166  sub_pct_blue                          7995 non-null   float64
 167  womens_fight                          7995 non-null   int64
 168  ratio_td_red                          7225 non-null   float64
 169  ratio_td_blue                         6391 non-null   float64
 170  ratio_control_red                     7225 non-null   float64
 171  ratio_control_blue                    6391 non-null   float64
 172  ratio_sigstrike_red                   7225 non-null   float64
 173  ratio_sigstrike_blue                  6391 non-null   float64
 174  ratio_td_diff                         6068 non-null   float64
 175  ratio_control_diff                    6068 non-null   float64
 176  ratio_sigstrike_diff                  6068 non-null   float64
 177  red_title_fights                      7995 non-null   float64
 178  blue_title_fights                     7995 non-null   float64
 179  red_title_wins                        7995 non-null   float64
 180  blue_title_wins                       7995 non-null   float64
 181  red_title_losses                      7995 non-null   float64
 182  blue_title_losses                     7995 non-null   float64
 183  red_title_win_pct                     7995 non-null   float64
 184  blue_title_win_pct                    7995 non-null   float64
 185  fighter_red                           7995 non-null   object
 186  fighter_blue                          7995 non-null   object
 187  red_fighter_stats                     7995 non-null   object
 188  blue_fighter_stats                    7995 non-null   object
 189  open_blue                             7058 non-null   float64
 190  close1_blue                           7058 non-null   float64
 191  close2_blue                           7058 non-null   float64
 192  open_red                              7058 non-null   float64
 193  close1_red                            7058 non-null   float64
 194  close2_red                            7058 non-null   float64
 195  event_date                            7058 non-null   object
 196  og_blue_name                          7058 non-null   object
 197  og_red_fighter                        6749 non-null   object
 198  dec_open_red                          7058 non-null   float64
 199  dec_close1_red                        7058 non-null   float64
 200  dec_close2_red                        7058 non-null   float64
 201  dec_open_blue                         7058 non-null   float64
 202  dec_close1_blue                       7058 non-null   float64
 203  dec_close2_blue                       7058 non-null   float64
 204  dec_fair_open_red                     7058 non-null   float64
 205  dec_fair_open_blue                    7058 non-null   float64
 206  proba_fair_open_red                   7058 non-null   float64
 207  proba_fair_open_blue                  7058 non-null   float64
 208  pimp_open_red                         7058 non-null   float64
 209  pimp_open_blue                        7058 non-null   float64
 210  dec_fair_close1_red                   7058 non-null   float64
 211  dec_fair_close1_blue                  7058 non-null   float64
 212  proba_fair_close1_red                 7058 non-null   float64
 213  proba_fair_close1_blue                7058 non-null   float64
 214  pimp_close1_red                       7058 non-null   float64
 215  pimp_close1_blue                      7058 non-null   float64
 216  dec_fair_close2_red                   7058 non-null   float64
 217  dec_fair_close2_blue                  7058 non-null   float64
 218  proba_fair_close2_red                 7058 non-null   float64
 219  proba_fair_close2_blue                7058 non-null   float64
 220  pimp_close2_red                       7058 non-null   float64
 221  pimp_close2_blue                      7058 non-null   float64
 222  juice_open_red                        7058 non-null   float64
 223  juice_close1_red                      7058 non-null   float64
 224  juice_close2_red                      7058 non-null   float64
 225  juice_open_blue                       7058 non-null   float64
 226  juice_close1_blue                     7058 non-null   float64
 227  juice_close2_blue                     7058 non-null   float64
 228  line_movement_close1_red              7058 non-null   float64
 229  line_movement_close1_blue             7058 non-null   float64
 230  line_movement_close2_red              7058 non-null   float64
 231  line_movement_close2_blue             7058 non-null   float64
 232  red_ud_to_fav_close1                  7058 non-null   object
 233  red_ud_to_fav_close2                  7058 non-null   object
 234  red_stayed_fav_close1                 7058 non-null   object
 235  red_stayed_fav_close2                 7058 non-null   object
 236  red_fav_to_ud_close1                  7058 non-null   object
 237  red_fav_to_ud_close2                  7058 non-null   object
 238  red_stayed_dog_close1                 7058 non-null   object
 239  red_stayed_dog_close2                 7058 non-null   object
 240  blue_ud_to_fav_close1                 7058 non-null   float64
 241  blue_ud_to_fav_close2                 7058 non-null   float64
 242  blue_stayed_fav_close1                7058 non-null   float64
 243  blue_stayed_fav_close2                7058 non-null   float64
 244  blue_fav_to_ud_close1                 7058 non-null   float64
 245  blue_fav_to_ud_close2                 7058 non-null   float64
 246  blue_stayed_dog_close1                7058 non-null   float64
 247  blue_stayed_dog_close2                7058 non-null   float64
 248  red_fighter_odds                      7058 non-null   object
 249  blue_fighter_odds                     7058 non-null   object
 250  fav_counts_red                        7995 non-null   int64
 251  dog_counts_red                        7995 non-null   int64
 252  fav_counts_blue                       7995 non-null   int64
 253  dog_counts_blue                       7995 non-null   int64
dtypes: float64(215), int64(17), object(22)
memory usage: 15.5+ MB

In [75]:
df_final.dropna().shape

(5118, 254)

In [79]:
non_feats = ['date','event_location', 'winner_name','red_fighter_stats', 'blue_fighter_stats', 'red_close1', 'blue_close1',
             'red_close2', 'blue_close2','event_date', 'og_red_fighter', 'og_blue_name', 'juice_close1_red', 'juice_close1_blue',
             'juice_close2_red','juice_close2_blue','pimp_close2_red', 'pimp_close1_red', 'pimp_close2_blue', 'pimp_close1_blue',
             'line_movement_close1_red', 'line_movement_close1_blue', 'line_movement_close2_red', 'line_movement_close2_blue',
             'red_ud_to_fav_close1', 'blue_ud_to_fav_close1', 'red_ud_to_fav_close2', 'blue_ud_to_fav_close2',
             'red_stayed_fav_close1', 'blue_stayed_fav_close1', 'red_stayed_fav_close2', 'blue_stayed_fav_close2',
             'red_fav_to_ud_close1', 'blue_fav_to_ud_close1', 'red_fav_to_ud_close2', 'blue_fav_to_ud_close2',
             'red_stayed_dog_close1', 'blue_stayed_dog_close1', 'red_stayed_dog_close2', 'blue_stayed_dog_close2',
             'red_fighter_odds', 'blue_fighter_odds', 'method']
             

y = 'winner'

In [80]:
set(df_final.columns) - set(non_feats)

{'age_blue',
 'age_diff',
 'age_red',
 'avg_fight_min_blue',
 'avg_fight_min_diff',
 'avg_fight_min_red',
 'blue_title_fights',
 'blue_title_losses',
 'blue_title_win_pct',
 'blue_title_wins',
 'body_str_pm_blue',
 'body_str_pm_diff',
 'body_str_pm_red',
 'body_str_total_blue',
 'body_str_total_diff',
 'body_str_total_red',
 'clinch_str_pm_blue',
 'clinch_str_pm_diff',
 'clinch_str_pm_red',
 'clinch_str_total_blue',
 'clinch_str_total_diff',
 'clinch_str_total_red',
 'close1_blue',
 'close1_red',
 'close2_blue',
 'close2_red',
 'control_pm_blue',
 'control_pm_diff',
 'control_pm_red',
 'control_total_blue',
 'control_total_diff',
 'control_total_red',
 'dec_close1_blue',
 'dec_close1_red',
 'dec_close2_blue',
 'dec_close2_red',
 'dec_fair_close1_blue',
 'dec_fair_close1_red',
 'dec_fair_close2_blue',
 'dec_fair_close2_red',
 'dec_fair_open_blue',
 'dec_fair_open_red',
 'dec_open_blue',
 'dec_open_red',
 'dec_pct_blue',
 'dec_pct_red',
 'decision_wins_blue',
 'decision_wins_diff',
 'decision_wins_red',
 'dog_counts_blue',
 'dog_counts_red',
 'elo_blue',
 'elo_diff',
 'elo_red',
 'fav_counts_blue',
 'fav_counts_red',
 'fight_otn_bonus',
 'fighter_blue',
 'fighter_red',
 'glicko_blue',
 'glicko_diff',
 'glicko_rd_blue',
 'glicko_rd_diff',
 'glicko_rd_red',
 'glicko_red',
 'head_str_pm_blue',
 'head_str_pm_diff',
 'head_str_pm_red',
 'head_str_total_blue',
 'head_str_total_diff',
 'head_str_total_red',
 'height_blue',
 'height_diff',
 'height_red',
 'juice_open_blue',
 'juice_open_red',
 'kd_pm_blue',
 'kd_pm_diff',
 'kd_pm_red',
 'kd_total_blue',
 'kd_total_diff',
 'kd_total_red',
 'ko_pct_blue',
 'ko_pct_red',
 'ko_wins_blue',
 'ko_wins_diff',
 'ko_wins_red',
 'leg_str_pm_blue',
 'leg_str_pm_diff',
 'leg_str_pm_red',
 'leg_str_total_blue',
 'leg_str_total_diff',
 'leg_str_total_red',
 'lose_streak_blue',
 'lose_streak_diff',
 'lose_streak_red',
 'losses_diff',
 'math_blue',
 'math_red',
 'months_since_blue',
 'months_since_diff',
 'months_since_red',
 'num_fights_blue',
 'num_fights_diff',
 'num_fights_red',
 'num_losses_blue',
 'num_losses_red',
 'num_wins_blue',
 'num_wins_red',
 'open_blue',
 'open_red',
 'performance_bonus_winner',
 'pimp_open_blue',
 'pimp_open_red',
 'proba_fair_close1_blue',
 'proba_fair_close1_red',
 'proba_fair_close2_blue',
 'proba_fair_close2_red',
 'proba_fair_open_blue',
 'proba_fair_open_red',
 'ratio_control_blue',
 'ratio_control_diff',
 'ratio_control_red',
 'ratio_sigstrike_blue',
 'ratio_sigstrike_diff',
 'ratio_sigstrike_red',
 'ratio_td_blue',
 'ratio_td_diff',
 'ratio_td_red',
 'reach_blue',
 'reach_diff',
 'reach_red',
 'red_title_fights',
 'red_title_losses',
 'red_title_win_pct',
 'red_title_wins',
 'reverse_pm_blue',
 'reverse_pm_diff',
 'reverse_pm_red',
 'reverse_total_blue',
 'reverse_total_diff',
 'reverse_total_red',
 'sig_str_absorbed_pm_blue',
 'sig_str_absorbed_pm_diff',
 'sig_str_absorbed_pm_red',
 'sig_str_absorbed_total_blue',
 'sig_str_absorbed_total_diff',
 'sig_str_absorbed_total_red',
 'sig_str_accuracy_pct_blue',
 'sig_str_accuracy_pct_red',
 'sig_str_attempted_pm_blue',
 'sig_str_attempted_pm_diff',
 'sig_str_attempted_pm_red',
 'sig_str_attempted_total_blue',
 'sig_str_attempted_total_diff',
 'sig_str_attempted_total_red',
 'sig_str_defense_pct_blue',
 'sig_str_defense_pct_red',
 'sig_str_landed_pm_blue',
 'sig_str_landed_pm_diff',
 'sig_str_landed_pm_red',
 'sig_str_landed_total_blue',
 'sig_str_landed_total_diff',
 'sig_str_landed_total_red',
 'sig_str_total_attempted_against_blue',
 'sig_str_total_attempted_against_red',
 'sig_str_total_landed_against_blue',
 'sig_str_total_landed_against_red',
 'sub_att_pm_blue',
 'sub_att_pm_diff',
 'sub_att_pm_red',
 'sub_att_total_blue',
 'sub_att_total_diff',
 'sub_att_total_red',
 'sub_pct_blue',
 'sub_pct_red',
 'sub_wins_blue',
 'sub_wins_diff',
 'sub_wins_red',
 'td_accuracy_pct_blue',
 'td_accuracy_pct_red',
 'td_attempted_pm_blue',
 'td_attempted_pm_diff',
 'td_attempted_pm_red',
 'td_attempted_total_blue',
 'td_attempted_total_diff',
 'td_attempted_total_red',
 'td_defense_pct_blue',
 'td_defense_pct_red',
 'td_landed_pm_blue',
 'td_landed_pm_diff',
 'td_landed_pm_red',
 'td_landed_total_blue',
 'td_landed_total_diff',
 'td_landed_total_red',
 'td_total_attempted_against_blue',
 'td_total_attempted_against_red',
 'td_total_landed_against_blue',
 'td_total_landed_against_red',
 'title_fight',
 'total_bonus_blue',
 'total_bonus_diff',
 'total_bonus_red',
 'total_fight_time_blue',
 'total_fight_time_red',
 'weight_class',
 'win_pct_blue',
 'win_pct_diff',
 'win_pct_red',
 'win_streak_blue',
 'win_streak_diff',
 'win_streak_red',
 'winner',
 'wins_diff',
 'womens_fight'}

In [72]:
fp = r'C:\Users\jcmar\my_files\SportsBetting\data\new_combined.csv'
df_combined = pd.read_csv(fp)   
df_combined['title_fight'][-15:]

C:\Users\jcmar\AppData\Local\Temp\ipykernel_46876\1516149698.py:2: DtypeWarning: Columns (79,83) have mixed types. Specify dtype option on import or set low_memory=False.
  df_combined = pd.read_csv(fp)

7992                       0.0
7993                       0.0
7994                       0.0
7995            Gabriel Bonfim
7996              Matt Schnell
7997           Muslim Salikhov
7998             Chris Padilla
7999    Christian Leroy Duncan
8000                Hyder Amil
8001               Ricky Simon
8002         Mayra Bueno Silva
8003                Josh Hokit
8004          Tecia Pennington
8005               Miles Johns
8006                Zach Reese
Name: title_fight, dtype: object

In [73]:
fp = r'C:\Users\jcmar\my_files\SportsBetting\data\ufc_new_rolling.csv'
df_rolling = pd.read_csv(fp)
df_rolling['title_fight'][-15:]

7992                       0.0
7993                       0.0
7994                       0.0
7995            Gabriel Bonfim
7996              Matt Schnell
7997           Muslim Salikhov
7998             Chris Padilla
7999    Christian Leroy Duncan
8000                Hyder Amil
8001               Ricky Simon
8002         Mayra Bueno Silva
8003                Josh Hokit
8004          Tecia Pennington
8005               Miles Johns
8006                Zach Reese
Name: title_fight, dtype: object

In [70]:
df_final['title_fight']

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
7990    0.0
7991    0.0
7992    0.0
7993    0.0
7994    0.0
Name: title_fight, Length: 7995, dtype: float64

In [68]:
duplicates = df_final.duplicated(subset=['fighter_red', 'fighter_blue', 'date'], keep=False)
dup_rows = df_final[duplicates]

non_duplicate_columns = [col for col in df_final.columns if dup_rows[col].nunique() > 1]

dup_rows[['fighter_red', 'fighter_blue', 'date', 'open_red', 'open_blue', 'close1_red', 'close1_blue', 'red_fighter_odds', 'blue_fighter_odds', 'red_fighter_stats', 'blue_fighter_stats']]

Empty DataFrame
Columns: [fighter_red, fighter_blue, date, open_red, open_blue, close1_red, close1_blue, red_fighter_odds, blue_fighter_odds, red_fighter_stats, blue_fighter_stats]
Index: []

In [ ]:
dup_rows[['fighter_red', 'fighter_blue', 'date', 'open_red', 'open_blue', 'close1_red', 'close1_blue']]

In [66]:
fp = r'C:\Users\jcmar\my_files\SportsBetting\data\look_at_odds.csv'
df_odds = pd.read_csv(fp)
duplicates = df_odds.duplicated(subset=['red_fighter', 'blue_fighter', 'date'], keep=False)
dup_rows = df_odds[duplicates]
dup_rows[['red_clean', 'blue_clean', 'date']]

          red_clean    blue_clean        date
1348  chris barnett  martin buday  2022-04-16
1349  chris barnett  martin buday  2022-04-16

In [37]:
fp = r'C:\Users\jcmar\my_files\SportsBetting\data\stats_history_2025-11-05.csv'
df_stats_history = pd.read_csv(fp)

In [38]:
df_stats_history['title_fight']

0       0
1       0
2       0
3       0
4       0
       ..
7990    1
7991    0
7992    0
7993    0
7994    0
Name: title_fight, Length: 7995, dtype: int64

In [35]:
set(df_stats_history['fighter_red']) - set(df_odds['red_fighter'])

{'AJ Dobson',
 'AJ Fletcher',
 'Alatengheili',
 'Aleksandra Albu',
 'Aleksei Kunchenko',
 'Alex Karalexis',
 'Ali AlQaisi',
 'Alvaro Herrera Mendoza',
 'Anthony Torres',
 'Anying Wang',
 'Asu Almabayev',
 'BJ Penn',
 'Baisangur Susurkaev',
 'Batgerel Danaa',
 'Benoit Saint Denis',
 'Bia Mesquita',
 'Bibulatov Magomed',
 'Blood Diamond',
 'Branden Lee Hinkle',
 'CB Dollaway',
 'CJ Vergara',
 'CM Punk',
 'Carls John De Tomas',
 'Carmelo Marrero',
 'Charles McCarthy',
 'Chris de la Rocha',
 'Clay Collard',
 'Cristian Quinonez',
 'Da Woon Jung',
 "Da'Mon Blackshear",
 'DaMarques Johnson',
 'Dan Christison',
 'David Heath',
 'David Terrell',
 'DeAnna Bennett',
 'Din Thomas',
 "Don'Tale Mayes",
 'Drew Fickett',
 'Edimilson Souza',
 'Ednaldo Oliveira',
 'Eduardo Garagorri',
 'Elizeu Zaleski dos Santos',
 'Evan Tanner',
 'Felipe dos Santos',
 'Francisco Figueiredo',
 'Francisco Prado',
 'Glaico Franca Moreira',
 'Grigory Popov',
 'Guangyou Ning',
 'Henrique da Silva',
 'HyunSung Park',
 'Ike Villanueva',
 'Ivan Salaverry',
 'JJ Aldrich',
 'JP Buys',
 'Jacare Souza',
 "Jake O'Brien",
 'Jason MacDonald',
 'Jason Von Flue',
 'Jeff Monson',
 'JeongYeong Lee',
 'Jeremy Horn',
 'Jorge Santiago',
 'Jose Maria',
 'Joseph Gigliotti',
 'Josh Sampo',
 'Joshua Burkman',
 'Joshua Van',
 'Juan Manuel Puig',
 'JunYong Park',
 'Junie Browning',
 'KJ Noons',
 'Kalib Starnes',
 'Kazula Vargas',
 'Kevin Ferguson',
 'Kuniyoshi Hironaka',
 'Logan Clark',
 'Luiz Cane',
 'Luiz Dutra',
 'Luke Cummo',
 'MarQuel Mederos',
 'Marcio Cruz',
 'Marco Tulio',
 'Marcus LeVesseur',
 'Mark De La Rosa',
 'Matt Lindland',
 'Matt Van Buren',
 'Matthew Riddle',
 'Mike Kyle',
 'Mike Nickels',
 'Mike de la Torre',
 'Mike van Arsdale',
 'Mizuki',
 'Montana De La Rosa',
 'Montse Rendon',
 'Nate Mohr',
 'Nick Thompson',
 'Ovince Saint Preux',
 'Paige VanZant',
 'Paul Buentello',
 'Pete Spratt',
 'Philip De Fries',
 'Rameau Thierry Sokoudjou',
 'Rayanne dos Santos',
 'Renee Forte',
 'Rob MacDonald',
 'Robert Sanchez',
 'Rogerio Nogueira',
 "Roldan Sangcha'an",
 'Rory MacDonald',
 'Rory Singer',
 'Ryan LaFlare',
 'Ryan MacDonald',
 'Sai Wang',
 'Sam Hoger',
 'Scott Smith',
 'SeungGuk Choi',
 'SeungWoo Choi',
 'Silvana Gomez Juarez',
 'SuYoung You',
 'Sumudaerji',
 'TJ Brown',
 'TJ Dillashaw',
 'TJ Grant',
 'TJ Waldburger',
 'Terry Martin',
 'Tiago dos Santos e Silva',
 'Tom Murphy',
 'Tony DeSouza',
 'Travis Lutter',
 'Trevor Prangley',
 'Vernon Ramos Ho',
 'Vinicius Oliveira',
 'Waldo Cortes Acosta',
 'Wendell Oliveira Marques',
 'Wulijiburen',
 'Yadier del Valle',
 'Yorgan De Castro',
 'Zhang Tiequan'}

In [36]:
set(df_odds['red_fighter']) - set(df_stats_history['fighter_red'])

{'A.J. Dobson',
 'A.J. Fletcher',
 'Aaron Beltran',
 'Aaron Chalmers',
 'Abubakar Vagaev',
 'Abusupiyan Magomedov',
 'Adrian Garcia',
 'Aj Dobson',
 'Alan Carlos',
 'Alan Gabriel',
 'Aleksei Oliynyk',
 'Alex Hernandez',
 'Alex Volkanovski',
 'Alexander Romanov',
 'Ali Alqaisi',
 'Alice Smith Yauger',
 'Aljamain Stirling',
 'Alvaro Herrera',
 'Ana Araujo',
 'Ana Martinez',
 'Andrei Arlovski.',
 'Angela Lee',
 'Antonio Rogerio Nogueira',
 'Asu Almabaev',
 'Azael Rodriguez',
 'B.J. Penn',
 'Beatriz Mesquita',
 'Benoit Saint-Denis',
 'Billy Goff',
 'Billy Quartantillo',
 'Blake Smith',
 'Brendan Lesar',
 'Brogan Walker-Sanchez',
 'Bryan Baker',
 'C.B. Dollaway',
 'C.J. Vergara',
 'Calvin Cattar',
 'Carlos Diego Ferreira',
 'Carls John de Tomas',
 'Casey Jones',
 'Charles Clark',
 'Charles Henrique',
 'Charles Lamptey',
 'Choi Doo-Ho',
 'Chris Padilla',
 'Chris de La Rocha',
 'Christian Duncan',
 'Christian Quinonez',
 'Cj Vergara',
 'Claudio Henrique da Silva',
 'Cm Punk',
 'Cody Brundage.',
 'Cody Chovancek',
 'Cong Wang',
 'Da Un Jung',
 "Da'mon Blackshear",
 'Dabdam Por Tor Tor Thongtawee',
 'Damarques Johnson',
 'Damon Blackshear',
 'Dan Arguetta',
 'Danaa Batgerel',
 'Daniel Argueta',
 'Daniel Hooker',
 'Darmon Blackshear',
 'Deandre Anderson',
 'Deanna Bennett',
 'Demetrius Wilson',
 "Don'tale Mayes",
 'Doo Ho Choi',
 'Douglas Evans',
 'Elismar Lima',
 'Elizeu Zaleski',
 'Elizeu Zaleski Dos Santos',
 'Evan Thompson',
 'Felipe Dos Santos',
 'Felipe Efrain',
 'Francisco Drinaldo',
 'Francisco Figueredo',
 'Gabriel Braga',
 'Gabriel Green',
 'Geoffrey Neal',
 'Gil de Freitas',
 'Glaico Franca',
 'Grigorii Popov',
 'Hayisaer Maheshate',
 'Hyun Sung Park',
 'Ian Garry',
 'J.J. Aldrich',
 'J.P. Buys',
 'Jacqueline Amorim',
 'Jake O Brien',
 'Jamey-Lyn Horth Wessels',
 'Jason Jackson',
 'Jason Macdonald',
 'Jeongyeong Lee',
 'Jeremy Henry',
 'Jerome Rivera',
 'Jessica Rakozczy',
 'Jesus Santos Aguilar',
 'Jim Crute',
 'Jingliang Li',
 'Jj Aldrich',
 'Joanne Calderwood',
 'Joe Gigliotti',
 'Johnny Munoz Jr',
 'Johnny Munoz Jr.',
 'Jon Delos Reyes',
 'Jorge Ortiz',
 'Jose Alday',
 'Jose Sanchez',
 'Josefin Knutsson',
 'Joselyne Edwards.',
 'Joseph Duffy',
 'Joseph Nathan Maness',
 'Josh Burkman',
 'Josh Hokit',
 'Joshua Culibao',
 'Joshua Sampo',
 'Joshua van',
 'Juan Puig',
 'Julia Stoliarenko',
 'Julian Lane',
 'Juliana Carneiro Lima',
 'Julio Cesar Neves',
 'Jun Yong Park',
 'K.J. Noons',
 'Kai Kamaka III',
 'Kai Kara France',
 'Kang Kyung-Ho',
 'Karl Albrektsson',
 'Karol Celinski',
 'Kenan Jackson',
 'Kenan Song',
 'Kennedy Nzechukwu.',
 'Khalil Rountree',
 'Khalil Rountree Jr',
 'Lina Akhtar Lansberg',
 'Lipeng Zhang',
 'Liu Pingyuan',
 'Long Xiao',
 'Luan Luiz Lacerda',
 'Luis Henrique da Silva',
 'Luiz Dutra Jr.',
 'Luiz Henrique Pacifico',
 'Magomed Bibulatov',
 'Maheshate Hayisaer',
 'Manny Gamburyan',
 'Marc Andre Barriault',
 'Marcio Alexandre Jr.',
 'Marco Antonio Beltran',
 'Marco Tulio Silva',
 'Marcos Rogerio',
 'Marcus Levesseur',
 'Mark de La Rosa',
 'Markus Perez Echeimberg',
 'Marquel Mederos',
 'Matt Riddle',
 'Matt van Buren',
 'Matthew Elliott',
 'Mayra Bueno',
 'Michelle Waterson',
 'Mike de La Torre',
 'Miles Jury',
 'Miles Lee',
 'Ming Shi',
 'Mingyang Zhang',
 'Mizuki Inoue',
 'Montana de La Rosa',
 'Montserrat Rendon',
 'Moraad Moreno',
 'Muhammadjon Naimov',
 'Na Liang',
 'Nathan Levy',
 'Nico Musoke',
 'Ning Guangyou',
 'Nuerdanbieke Shayilan',
 "Ode' Osbourne",
 'Orlando Mendoza',
 'Ovince St. Preux',
 'Paige Vanzant',
 'Park Hyun-Sung',
 'Patrick Bittencourt',
 'Patrick Downey',
 'Phil de Fries',
 'Philip de Fries',
 'Phillip Hawes',
 'Phillip Rowe',
 'Polo Reyes',
 'Puna Soriano',
 'Rameau Sokoudjou',
 'Raul Rosas Jr',
 'Rayanne Dos Santos',
 'Ricardo Lucas Ramos',
 'Rick Glenn',
 'Ro Montana',
 'Roldan Sangcha-An',
 'Roman Dolideze',
 'Rory Macdonald',
 'Ryan Laflare',
 'Ryan Macdonald',
 'Sean Carter',
 'Sergey Pavlovich',
 'Sergio Rios',
 'Seung Guk Choi',
 'Seung Woo Choi',
 'Seungwoo Choi',
 'Shamil Abdurahimov',
 'Silvana Gomez Juarez.',
 'Stephanie Page',
 'Su Young You',
 'Sumudaerji Sumudaerji',
 'T.J. Dillashaw',
 'T.J. Grant',
 'T.J. Waldburger',
 'Thiago de Oliveira Perpetuo',
 'Tiequan Zhang',
 'Timothy Cuamba',
 'Timothy Elliott',
 'Urijah Hall',
 'Vernon Ramos',
 'Victoria Dudakova',
 'Waldo Cortes-Acosta',
 'Wang Anying',
 'Wang Sai',
 'Weili Zhang',
 'Wendell Oliveira',
 'William Gomi',
 'Xiaonan Yan',
 'Yadier Delvalle',
 'Yadong Song',
 'Yanan Wu',
 'Yorgan de Castro',
 'Yuri Alcantara',
 'Zach Reese'}

In [ ]:
df_combined.info(verbose=True, show_counts=True)

In [ ]:
df_rolling.info()

In [15]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8007 entries, 0 to 8006
Columns: 179 entries, td_defense_pct_red to ratio_sigstrike_diff
dtypes: float64(158), int64(12), object(9)
memory usage: 10.9+ MB

In [9]:
df_rolling['event_location'].unique()

array([' USA', ' United Kingdom', ' Canada', ' Ireland', ' Germany',
       ' Australia', ' United Arab Emirates', ' Brazil', ' Japan',
       ' Sweden', ' China', ' Singapore', ' New Zealand', ' Mexico',
       ' Poland', ' Philippines', ' South Korea', ' Croatia',
       ' Netherlands', ' Chile', ' Russia', ' Argentina',
       ' Czech Republic', ' Uruguay', ' Denmark', ' France',
       ' Saudi Arabia', ' Azerbaijan'], dtype=object)

In [2]:
for c in df_combined.columns: 
    if df_combined[c].isna().sum() > 3000: 
        print(c, '  ',df_combined[c].isna().sum())

NameError: name 'df_combined' is not defined

In [32]:
df_combined['sig_str_landed_total_red'].isna().sum()

np.int64(772)

In [37]:
df_combined['sig_str_landed_total_red'].tail(20)

7987     566.0
7988     125.0
7989       NaN
7990     303.0
7991     312.0
7992     122.0
7993      55.0
7994     259.0
7995     227.0
7996     502.0
7997     425.0
7998     119.0
7999     324.0
8000     239.0
8001     540.0
8002     503.0
8003       NaN
8004    1199.0
8005     476.0
8006       NaN
Name: sig_str_landed_total_red, dtype: float64

In [18]:
print(df_combined['td_landed_total_red'].isna().sum())

772

In [23]:
print(type(df_combined['td_landed_total_red'].iloc[-1]))

<class 'numpy.float64'>

In [15]:
test_csv = pd.read_csv(r'C:\Users\jcmar\my_files\SportsBetting\data\all_stats_v2.csv')

In [27]:
duplicates = odds_stats.groupby(['red_fighter', 'blue_fighter','date']).size().reset_index(name='count').query('count>1')
print(duplicates)
dup_keys = duplicates[['red_fighter', 'blue_fighter', 'date']]

duplicate_rows = odds_stats.merge(
    dup_keys,
    on=['red_fighter', 'blue_fighter', 'date'],
    how='inner'
)

for name, group in duplicate_rows.groupby(['red_fighter', 'blue_fighter', 'date']):
    print(f"\nGroup: {name}")
    # print(group)

    group_no_index = group.drop(columns=['red_fighter', 'blue_fighter', 'date'])
    
    # Find which columns have more than one unique value
    diff_cols = group_no_index.nunique()[group_no_index.nunique() > 1].index.tolist()

    if len(diff_cols) == 0:
        print("✅ All rows in this group are exactly the same.")
    else:
        print("⚠️ These columns differ between rows:", diff_cols)

           red_fighter        blue_fighter       date  count
1239     chris barnett        martin buday 2022-04-16      2
1595    curtis blaydes       rizvan kuniev 2025-06-21      2
2884  hamdy abdelwahab      mohammed usman 2025-06-21      2
3020   irina alekseeva      klaudia sygula 2025-06-21      2
5146      max holloway      dustin poirier 2025-07-19      2
6030     rafael fiziev  ignacio bahamondes 2025-06-21      2
6379  robert whittaker   reinier de ridder 2025-07-26      2
6735      seokhyeon ko        oban elliott 2025-06-21      2
6982   tagir ulanbekov         azat maksum 2025-06-21      2
7284     tofiq musayev    myktybek orolbai 2025-06-21      2

Group: ('chris barnett', 'martin buday', Timestamp('2022-04-16 00:00:00'))
⚠️ These columns differ between rows: ['open_blue', 'close1_blue', 'close2_blue', 'open_red', 'close1_red', 'close2_red']

Group: ('curtis blaydes', 'rizvan kuniev', Timestamp('2025-06-21 00:00:00'))
⚠️ These columns differ between rows: ['close1_blue', 'close2_red']

Group: ('hamdy abdelwahab', 'mohammed usman', Timestamp('2025-06-21 00:00:00'))
⚠️ These columns differ between rows: ['close1_blue', 'close2_blue', 'close1_red', 'close2_red']

Group: ('irina alekseeva', 'klaudia sygula', Timestamp('2025-06-21 00:00:00'))
⚠️ These columns differ between rows: ['close1_blue', 'close1_red', 'close2_red']

Group: ('max holloway', 'dustin poirier', Timestamp('2025-07-19 00:00:00'))
⚠️ These columns differ between rows: ['close1_blue', 'close2_blue', 'close1_red', 'close2_red']

Group: ('rafael fiziev', 'ignacio bahamondes', Timestamp('2025-06-21 00:00:00'))
⚠️ These columns differ between rows: ['close2_red']

Group: ('robert whittaker', 'reinier de ridder', Timestamp('2025-07-26 00:00:00'))
⚠️ These columns differ between rows: ['close1_blue', 'close1_red', 'close2_red']

Group: ('seokhyeon ko', 'oban elliott', Timestamp('2025-06-21 00:00:00'))
⚠️ These columns differ between rows: ['close1_red']

Group: ('tagir ulanbekov', 'azat maksum', Timestamp('2025-06-21 00:00:00'))
⚠️ These columns differ between rows: ['close2_blue', 'close1_red']

Group: ('tofiq musayev', 'myktybek orolbai', Timestamp('2025-06-21 00:00:00'))
⚠️ These columns differ between rows: ['close1_blue', 'close2_blue', 'close1_red', 'close2_red']

In [28]:
result = odds_stats[odds_stats['blue_fighter'].str.contains('Poirier', case=False, na=False)]

result.tail()

,control_pr_red,td_pr_red,sub_att_pr_red,sigstrikes_pm_red,head_strikes_pm_red,leg_strikes_pm_red,body_strikes_pm_red,clinch_strikes_pm_red,ground_strikes_pm_red,kd_pr_red,...,red_fighter_stats,blue_fighter_stats,open_blue,close1_blue,close2_blue,open_red,close1_red,close2_red,red_fighter_odds,blue_fighter_odds
4865,147.122727,1.510606,0.162121,4.044848,3.558788,0.186364,0.299697,0.159091,2.500909,0.121212,...,Khabib Nurmagomedov,Dustin Poirier,205.0,315.0,350.0,-240.0,-455.0,-400.0,Khabib Nurmagomedov,Dustin Poirier
5945,49.363095,0.625000,0.684524,2.095238,1.167857,0.415476,0.511905,0.375000,0.425000,0.119048,...,Charles Oliveira,Dustin Poirier,-165.0,-143.0,-130.0,145.0,110.0,120.0,Charles Oliveira,Dustin Poirier
7194,107.465556,0.825556,0.372222,2.053111,1.416000,0.108000,0.529111,0.402000,0.693333,0.188889,...,Islam Makhachev,Dustin Poirier,280.0,300.0,350.0,-400.0,-500.0,-400.0,Islam Makhachev,Dustin Poirier
7775,15.903333,0.072778,0.102222,6.394667,4.268889,0.617000,1.508778,0.534000,0.403222,0.156667,...,Max Holloway,Dustin Poirier,110.0,-120.0,100.0,-130.0,-127.0,-108.0,Max Holloway,Dustin Poirier
7776,15.903333,0.072778,0.102222,6.394667,4.268889,0.617000,1.508778,0.534000,0.403222,0.156667,...,Max Holloway,Dustin Poirier,110.0,-110.0,-102.0,-130.0,-122.0,-110.0,Max Holloway,Dustin Poirier