In [1]:
import numpy as np 
import pandas as pd 
from collections import defaultdict
 
import seaborn as sns 
import matplotlib.pyplot as plt

In [13]:
df_v2 = pd.read_csv(r'C:\Users\jcmar\my_files\SportsBetting\data\entire_odds_stats_2025-11-23.csv')
df_v2 = df_v2.sort_values('date').reset_index(drop=True)
df_v2 = df_v2[df_v2['winner']!=2].reset_index(drop=True)
# df_v2 = df_v2.dropna().reset_index(drop=True)

# df_non_rolling = pd.read_csv(r'C:\Users\jcmar\my_files\SportsBetting\data\new_combined.csv')
# print(df_v2.shape, df_non_rolling.shape)

In [15]:
fighters_red = df_v2[['fighter_red', 'elo_red','date']].rename(columns={'fighter_red': 'fighter', 'elo_red': 'elo'})
fighters_blue = df_v2[['fighter_blue', 'elo_blue', 'date']].rename(columns={'fighter_blue': 'fighter', 'elo_blue': 'elo'})
print(fighters_blue.columns)

all_fighters = pd.concat([fighters_red, fighters_blue], ignore_index=True)
all_fighters = all_fighters.sort_values('date')   # or whatever your chronological column is

top_fighters = all_fighters.groupby('fighter')['elo'].last().sort_values(ascending=False)


top_10_fighters = top_fighters.head(50)
top_10_fighters

Index(['fighter', 'elo', 'date'], dtype='object')

fighter
islam makhachev          1832.942995
georges st pierre        1809.563169
merab dvalishvili        1792.668264
jon jones                1791.324718
khabib nurmagomedov      1778.101574
leon edwards             1763.059800
nassourdine imavov       1761.965670
daniel cormier           1757.996170
grant dawson             1753.874438
khamzat chimaev          1752.958742
ilia topuria             1752.788454
demetrious johnson       1751.528563
max holloway             1750.107646
kamaru usman             1748.422241
francis ngannou          1745.621434
amanda nunes             1741.738944
alex pereira             1738.935012
alexander volkanovski    1733.289372
charles oliveira         1732.409702
aljamain sterling        1730.306861
beneil dariush           1725.735244
alexandre pantoja        1725.377671
rinat fakhretdinov       1722.319294
dricus du plessis        1720.200858
movsar evloev            1719.440161
jack della maddalena     1719.097157
deiveson figueiredo      1716.076357
magomed ankalaev         1714.663294
zhang weili              1709.535525
belal muhammad           1708.351262
bryan battle             1707.514317
carlos ulberg            1707.054909
ciryl gane               1705.465400
ryan bader               1703.827989
shavkat rakhmonov        1702.182774
arman tsarukyan          1701.930937
anthony hernandez        1698.792383
stipe miocic             1695.166052
brendan allen            1694.766406
sean brady               1692.925234
jan blachowicz           1692.083636
tom aspinall             1688.528930
alexander volkov         1688.350817
ian machado garry        1686.832771
benson henderson         1683.085483
gegard mousasi           1682.059153
youssef zalal            1679.830641
norma dumont             1678.131406
jimmy crute              1676.882748
randy brown              1676.627042
Name: elo, dtype: float64

In [32]:
df_test = pd.read_csv(r'C:\Users\jcmar\my_files\SportsBetting\data\new_combined.csv')

In [33]:
red_ratings = df_test[['fighter_red', 'glicko_red']].rename(
    columns={'fighter_red': 'fighter', 'glicko_red': 'rating'}
)
blue_ratings = df_test[['fighter_blue', 'glicko_blue']].rename(
    columns={'fighter_blue': 'fighter', 'glicko_blue': 'rating'}
)

all_ratings = pd.concat([red_ratings, blue_ratings], ignore_index=True)

# Find peak rating per fighter
peak_ratings = all_ratings.groupby('fighter')['rating'].max().reset_index()

# Sort descending
peak_ratings = peak_ratings.sort_values('rating', ascending=False).reset_index(drop=True)

# Show top 10 fighters by peak rating
print(peak_ratings.head(10))

             fighter        rating
0      Jamall Emmers  20196.898983
1       Shannon Ross  14118.090308
2        Zarah Fairn  14118.090308
3     Ramiz Brahimaj  13593.930188
4  Ariane Carnelossi   9228.678571
5  Gillian Robertson   9189.134035
6       Molly McCann   8731.164252
7       Grant Dawson   8649.003266
8       Sean Soriano   6993.796463
9         Aoriqileng   6487.973790

In [34]:
df_test['winner'] = df_test['winner']
df_test['choice_elo'] = np.where(df_test['elo_red'] > df_test['elo_blue'], 1, 0)

df_test['choice_correct'] = np.where(df_test['choice_elo']==df_test['winner'], 1, 0)
print(df_test['choice_correct'].mean())

0.8975896090920444

In [3]:
fighters_red = df_v2[['fighter_red', 'glicko_red']].rename(columns={'fighter_red': 'fighter', 'glicko_red': 'glicko'})
fighters_blue = df_v2[['fighter_blue', 'glicko_blue']].rename(columns={'fighter_blue': 'fighter', 'glicko_blue': 'glicko'})

all_fighters = pd.concat([fighters_red, fighters_blue], ignore_index=True)
top_fighters = all_fighters.groupby('fighter')['glicko'].max().sort_values(ascending=False)
top_10_fighters = top_fighters.head(50)
top_10_fighters

fighter
ariane carnelossi         3706.285221
aoriqileng                3513.680856
gillian robertson         3508.537855
elves brener              3498.432696
ignacio bahamondes        3481.271381
miranda maverick          3471.261911
chase sherman             3462.826886
miesha tate               3422.999544
marcos rogerio de lima    3413.869263
scott holtzman            3391.883359
jack hermansson           3307.496490
joosang yoo               3304.433032
ovince st preux           3265.294222
ricky turcios             3248.895905
shauna bannon             3245.867780
mickey gall               3219.659327
austin vanderford         3215.026056
veronica hardy            3211.754834
martin buday              3203.640733
jean matsumoto            3203.299565
ismail naurdiev           3191.675084
quillan salkilld          3169.289517
drew dober                3169.202136
jose delgado              3163.205846
karolina kowalkiewicz     3139.067206
sam patterson             3120.521806
dustin jacoby             3118.503861
mohammad yahya            3113.221836
quang le                  3108.159996
ramon taveras             3091.550616
djorden santos            3089.923175
bruno silva               3089.235184
austin hubbard            3077.447775
tagir ulanbekov           3066.027074
alibi idiris              3058.488567
rafael cerqueira          3055.270956
kaue fernandes            3051.756299
viviane araujo            3047.734641
ilia topuria              3041.190154
punahele soriano          3040.034237
brandon moreno            3039.852182
blake bilder              3032.727709
joshua van                3025.332759
val woodburn              3022.709369
ricky simon               3017.232143
jonathan micallef         3005.503411
joseph morales            3002.768680
karine silva              3001.027331
melsik baghdasaryan       2983.158030
deiveson figueiredo       2978.514701
Name: glicko, dtype: float64

In [12]:
upcoming_df = pd.read_csv(r'C:\Users\jcmar\my_files\SportsBetting\data\upcoming_odds_stats_2025-11-08.csv')
upcoming_df.head(15)[['fighter_red','fighter_blue']]

               fighter_red           fighter_blue
0           gabriel bonfim            randy brown
1             matt schnell         joseph morales
2          muslim salikhov             uros medic
3            chris padilla          ismael bonfim
4   christian leroy duncan            marco tulio
5               hyder amil          jamall emmers
6              ricky simon         raoni barcelos
7        mayra bueno silva  jacqueline cavalcanti
8               josh hokit            max gimenis
9         tecia pennington           denise gomes
10             miles johns          daniel marcos
11              zach reese          jackson mcvey

In [9]:
red_ratings = df_v2[['fighter_red', 'glicko_red']].rename(
    columns={'fighter_red': 'fighter', 'glicko_red': 'rating'}
)
blue_ratings = df_v2[['fighter_blue', 'glicko_blue']].rename(
    columns={'fighter_blue': 'fighter', 'glicko_blue': 'rating'}
)

all_ratings = pd.concat([red_ratings, blue_ratings], ignore_index=True)

# Find peak rating per fighter
peak_ratings = all_ratings.groupby('fighter')['rating'].max().reset_index()

# Sort descending
peak_ratings = peak_ratings.sort_values('rating', ascending=False).reset_index(drop=True)

# Show top 10 fighters by peak rating
print(peak_ratings.head(10))

              fighter       rating
0   ariane carnelossi  3706.285221
1   gillian robertson  3508.537855
2  ignacio bahamondes  3481.271381
3    miranda maverick  3471.261911
4       chase sherman  3462.826886
5         miesha tate  3422.999544
6      scott holtzman  3391.883359
7     jack hermansson  3307.496490
8     ovince st preux  3265.294222
9       ricky turcios  3248.895905

In [33]:
df_v2[['elo_red']]

      elo_red
0      1500.0
1      1500.0
2      1500.0
3      1500.0
4      1500.0
...       ...
7990   1500.0
7991   1500.0
7992   1500.0
7993   1500.0
7994   1500.0

[7995 rows x 1 columns]